In [1]:
import warnings
warnings.filterwarnings('ignore')   #prevent warning
import pandas as pd                 #for reading dataset
import numpy as np                  #for linear algebra

In [2]:
df=pd.read_csv('insurance.csv')

In [3]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
#convert categorical value into numeric value using label encoder
from sklearn.preprocessing import LabelEncoder

In [6]:
le=LabelEncoder()   #creating an object

In [7]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [8]:
#using 'for loop' to convert categorical value into numeric value
for col in df.columns:
    if df[col].dtypes==np.number:
        continue
    else:
        df[col]=le.fit_transform(df[col])

In [9]:
df.head()

age  sex     bmi  children  smoker  region      charges
0    1    0  27.900         0       1       3  16884.92400
1    0    1  33.770         1       0       2   1725.55230
2   10    1  33.000         3       0       2   4449.46200
3   15    1  22.705         0       0       1  21984.47061
4   14    1  28.880         0       0       1   3866.85520

In [10]:
#for scaling using standardization
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()   #creating an object

In [11]:
for col1 in df.columns:
    df[col1]=scaler.fit_transform(df[[col1]])

In [12]:
df.head()

age       sex       bmi  children    smoker    region   charges
0 -1.438764 -1.010519 -0.453320 -0.908614  1.970587  1.343905  0.298584
1 -1.509965  0.989591  0.509621 -0.078767 -0.507463  0.438495 -0.953689
2 -0.797954  0.989591  0.383307  1.580926 -0.507463  0.438495 -0.728675
3 -0.441948  0.989591 -1.305531 -0.908614 -0.507463 -0.466915  0.719843
4 -0.513149  0.989591 -0.292556 -0.908614 -0.507463 -0.466915 -0.776802

In [13]:
df1=df.copy()

In [14]:
df1.head()

age       sex       bmi  children    smoker    region   charges
0 -1.438764 -1.010519 -0.453320 -0.908614  1.970587  1.343905  0.298584
1 -1.509965  0.989591  0.509621 -0.078767 -0.507463  0.438495 -0.953689
2 -0.797954  0.989591  0.383307  1.580926 -0.507463  0.438495 -0.728675
3 -0.441948  0.989591 -1.305531 -0.908614 -0.507463 -0.466915  0.719843
4 -0.513149  0.989591 -0.292556 -0.908614 -0.507463 -0.466915 -0.776802

In [15]:
#Divide x and y
x=df1[['age','sex','bmi','children','smoker','region']]
y=df1['charges']

In [16]:
x

age       sex       bmi  children    smoker    region
0    -1.438764 -1.010519 -0.453320 -0.908614  1.970587  1.343905
1    -1.509965  0.989591  0.509621 -0.078767 -0.507463  0.438495
2    -0.797954  0.989591  0.383307  1.580926 -0.507463  0.438495
3    -0.441948  0.989591 -1.305531 -0.908614 -0.507463 -0.466915
4    -0.513149  0.989591 -0.292556 -0.908614 -0.507463 -0.466915
...        ...       ...       ...       ...       ...       ...
1333  0.768473  0.989591  0.050297  1.580926 -0.507463 -0.466915
1334 -1.509965 -1.010519  0.206139 -0.908614 -0.507463 -1.372326
1335 -1.509965 -1.010519  1.014878 -0.908614 -0.507463  0.438495
1336 -1.296362 -1.010519 -0.797813 -0.908614 -0.507463  1.343905
1337  1.551686 -1.010519 -0.261388 -0.908614  1.970587 -0.466915

[1338 rows x 6 columns]

In [17]:
y

0       0.298584
1      -0.953689
2      -0.728675
3       0.719843
4      -0.776802
          ...   
1333   -0.220551
1334   -0.914002
1335   -0.961596
1336   -0.930362
1337    1.311053
Name: charges, Length: 1338, dtype: float64

In [18]:
from sklearn.model_selection import train_test_split as tts

In [19]:
#train 70%; test=30%
xtrain, xtest, ytrain, ytest = tts(x,y,test_size=.30)

In [20]:
xtrain.head()

age       sex       bmi  children    smoker    region
782   0.839674  0.989591  0.870519 -0.078767 -0.507463  0.438495
1192  1.338082 -1.010519  0.284060 -0.078767 -0.507463 -1.372326
249  -0.726752  0.989591 -0.276972 -0.078767 -0.507463 -1.372326
244   1.694088 -1.010519 -0.479567 -0.908614  1.970587 -1.372326
670  -0.655551  0.989591  0.148723  1.580926 -0.507463  0.438495

In [21]:
ytrain.head()

782    -0.320868
1192   -0.020756
249    -0.762453
244     1.342593
670    -0.696613
Name: charges, dtype: float64

In [22]:
xtest.head()

age       sex       bmi  children    smoker    region
559 -1.438764  0.989591  0.798339 -0.908614 -0.507463 -0.466915
354 -1.509965 -1.010519  1.249462 -0.908614 -0.507463  0.438495
243  0.056461  0.989591  0.760609  1.580926 -0.507463  1.343905
877 -0.441948  0.989591  0.455486  3.240619 -0.507463  0.438495
52   0.626070  0.989591 -0.436916 -0.078767  1.970587  1.343905

In [23]:
ytest.head()

559   -0.960225
354    0.071258
243   -0.501719
877   -0.546581
52     0.850676
Name: charges, dtype: float64

# Linear Regression

In [24]:
from sklearn.linear_model import LinearRegression 

In [25]:
reg = LinearRegression()      #creating an object

In [26]:
reg.fit(xtrain,ytrain)        #training

LinearRegression()

In [27]:
#finding coefficient
m=reg.coef_
m

array([ 0.30052266, -0.00156369,  0.17573468,  0.04155863,  0.77231728,
       -0.01448252])

In [28]:
#finding intercept
c=reg.intercept_
c

-0.017095856208561588

In [30]:
m1,m2,m3,m4,m5,m6=0.30052266, -0.00156369,  0.17573468,  0.04155863,  0.77231728,-0.01448252
     
x1,x2,x3,x4,x5,x6=0.839674 ,0.989591,0.870519,-0.078767,-0.507463,0.438495
c=-0.017095856208561588
y=m1*x1 +m2*x2 +m3*x3 +m4*x4 +m5*x5+m6*x6+c
y


-0.01486823292484159

In [32]:
reg.predict([[-1.509965,0.989591,0.509621,-0.078767,-0.507463,0.438495]])

array([-0.78441029])

In [33]:
pred=reg.predict(xtest)

In [34]:
pred

array([-0.73364977, -0.68575457, -0.21369466, -0.33501111,  1.59190535,
       -1.01520907,  1.43662291, -0.63226237, -1.09403711,  1.52464897,
        0.00695394, -0.17130529, -0.98672482,  0.04315107, -0.23567699,
       -0.35397321, -0.84909945, -0.60779903,  0.31903684, -0.2051771 ,
        2.19976323, -0.21221807,  1.10366628, -0.16462504, -0.04848232,
       -0.20361871, -0.08165077, -0.67343908, -0.67666681, -0.34545772,
       -0.57880206, -0.19243473, -0.83418482, -0.00502127, -0.90294113,
        0.10208467, -0.29439021, -0.78894846,  0.10373616, -0.12168221,
        1.82253015, -0.39061527, -0.65216255, -0.17295922, -0.00349004,
       -0.11049101, -0.92354452, -0.19537725, -0.07219384, -0.17684485,
        0.04219608, -0.60643316,  2.04045083, -0.1518658 , -0.90060606,
       -0.799637  ,  0.27551489,  1.63584659, -0.20844407, -1.25400067,
       -0.19628024, -0.77692576,  1.91712722,  0.24720889, -0.86619749,
       -0.61887505,  1.70566326,  0.24867582,  0.16423539, -0.27

In [36]:
df1['predicted result']=reg.predict(x)

In [37]:
df1.head()

age       sex       bmi  children    smoker    region   charges  \
0 -1.438764 -1.010519 -0.453320 -0.908614  1.970587  1.343905  0.298584   
1 -1.509965  0.989591  0.509621 -0.078767 -0.507463  0.438495 -0.953689   
2 -0.797954  0.989591  0.383307  1.580926 -0.507463  0.438495 -0.728675   
3 -0.441948  0.989591 -1.305531 -0.908614 -0.507463 -0.466915  0.719843   
4 -0.513149  0.989591 -0.292556 -0.908614 -0.507463 -0.466915 -0.776802   

   predicted result  
0          0.937133  
1         -0.784410  
2         -0.523658  
3         -0.803807  
4         -0.647190

In [38]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [39]:
mse=mean_squared_error(ytest,pred)

In [40]:
mse

0.24061566010547128

In [41]:
mae=mean_absolute_error(ytest,pred)

In [42]:
mae

0.3257116566709134

In [43]:
r2_score(ytest,pred)

0.7637210742387341

# KNN Regression

In [44]:
from sklearn.neighbors import KNeighborsRegressor

In [45]:
neigh = KNeighborsRegressor(n_neighbors=5)   #crating an object

In [46]:
neigh.fit(xtrain,ytrain)                     #training

KNeighborsRegressor()

In [47]:
pred1=neigh.predict(xtest)

In [48]:
pred1

array([-6.36735603e-01, -9.61411827e-01, -5.48349803e-01, -5.85779158e-01,
        1.55036378e+00, -6.83788642e-01,  2.13721719e+00, -8.79985131e-01,
       -9.57619582e-01,  2.37920569e+00, -4.51825249e-01, -9.45993795e-02,
       -7.23743660e-01, -1.20901793e-01, -5.25326986e-01,  1.71573428e-01,
       -6.33976220e-01, -3.53275288e-01,  1.39225034e-01, -1.71512275e-01,
        2.72479191e+00, -3.91029524e-01,  1.65942550e+00, -3.48626563e-01,
       -3.15033892e-02,  2.76489161e-01,  2.06606358e-02, -1.24673052e-01,
       -1.94153297e-01, -5.57789761e-01, -6.13844475e-01, -4.67336418e-01,
       -3.50647001e-01, -1.91068576e-01, -4.47790407e-01, -1.61237000e-01,
       -4.67332335e-01, -8.35719815e-01,  2.59416632e-01, -1.13572732e-01,
        2.43652007e+00, -3.62020795e-01, -5.44989151e-01, -2.10110175e-01,
        1.09541851e-01, -1.46814859e-01, -7.31527229e-01, -3.70149170e-01,
        9.43518850e-02,  1.74415932e-01, -2.49319458e-02, -9.46833361e-01,
        2.30146045e+00, -

In [49]:
mse=mean_squared_error(ytest,pred1)

In [50]:
mse

0.1973130321138236

In [51]:
mae= mean_absolute_error(ytest,pred1)

In [52]:
mae

0.26319837381752503

In [53]:
#measuring accuracy
r2_score(ytest,pred1)

0.8062432376757331

# Compare r2_score between Linear Regression and KNN Regression

In [ ]:
For Linear Regression r2_score=76% and for KNN Regression r2_score=80%.